version: "3.9"
services:
  postgres1:
    container_name: "Library_Container"
    image: postgres:14.5
    environment:
      POSTGRES_DB: "ЯКОВЛЕВ_БПИ206"
      POSTGRES_USER: "ЯКОВЛЕВ_БПИ206"
      POSTGRES_PASSWORD: "ЯКОВЛЕВ_БПИ206"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./docker/db/scripts/Library:/docker-entrypoint-initdb.d
      - ./docker/db/data/Library:/var/lib/postgresql/data
      - ./docker/db/config/Library:/var/lib/postgresql/data/pgdata/postgresql.conf
    ports:
      - "5432:5432"

  postgres2:
    container_name: "Hospital_Container"
    image: postgres:14.5
    environment:
      POSTGRES_DB: "ЯКОВЛЕВ_БПИ206"
      POSTGRES_USER: "ЯКОВЛЕВ_БПИ206"
      POSTGRES_PASSWORD: "ЯКОВЛЕВ_БПИ206"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./docker/db/scripts/Hospital:/docker-entrypoint-initdb.d
      - ./docker/db/data/Hospital:/var/lib/postgresql/data
      - ./docker/db/config/Hospital:/var/lib/postgresql/data/pgdata/postgresql.conf
    ports:
      - "5433:5432"

  postgres3:
    container_name: "Train_Container"
    image: postgres:14.5
    environment:
      POSTGRES_DB: "ЯКОВЛЕВ_БПИ206"
      POSTGRES_USER: "ЯКОВЛЕВ_БПИ206"
      POSTGRES_PASSWORD: "ЯКОВЛЕВ_БПИ206"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./docker/db/scripts/Train:/docker-entrypoint-initdb.d
      - ./docker/db/data/Train:/var/lib/postgresql/data
      - ./docker/db/config/Train:/var/lib/postgresql/data/pgdata/postgresql.conf
    ports:
      - "5434:5432"